version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pharmaplus
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: pharmaplus
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
